### ISSUE TITLE
No se muestra "select" en método de pago

### ISSUE THREAD

**Issue by doble-o** [PagaMasTarde/prestashop#1]
¿Qué cambios en configuración o código hay que realizar para mostrar el select en la página de pago del pedido como se muestra en la demo de PrestaShop?

https://imgur.com/a/kcFDTBt

Versión PrestaShop: 1.7.5.0
Versión módulo: 7.2.3

¡Gracias!

**Comment by rmarinleal** [comment]
Buenos días,
Perdón por la tardanza en contestar.
Nuestras versiones 7.x del módulo han dejado de ofrecer el simulador en el checkout por incompatibilidad con muchos de nuestros merchants, por lo que le ofrecemos 2 opciones:

Instalar una versión anterior la (6.2.3 por ejemplo) que si lo traía, o esperar a las nuevas releases 8.x que saldrán pronto con el simulador mejorado y más compatible.

Saludos.
